[tool.poetry]
name = "financial-calculator"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
Click = "^7.1.2"
fastapi = "^0.61.1"
uvicorn = "^0.12.2"
numpy = "^1.19.4"
scipy = "^1.5.3"
httpie = "^2.3.0"
pandas = "^1.1.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
